import { Difficulty, Language } from "@/generated/prisma";

export interface SampleProblem {
  title: string;
  difficulty: Difficulty;
  tags: string[];
  description: string;
  input: string;
  output: string;
  explanation: string;
  constraints: string;
  hints: string;
  editorial: string;
  testCases: Array<{
    input: string;
    expectedOutput: string;
    isSample: boolean;
    isHidden: boolean;
    explanation: string;
    order: number;
  }>;
  codeSnippets: Array<{
    language: Language;
    code: string;
  }>;
  solutions: Array<{
    language: Language;
    code: string;
  }>;
}

export const SAMPLE_PROBLEMS: Record<string, SampleProblem> = {
  "binary-search": {
    title: "Binary Search",
    difficulty: Difficulty.EASY,
    tags: ["arrays", "binary-search", "search"],
    description: [
      "Given an array of integers `nums` sorted in ascending order, and an integer `target`, write a function to search `target` in `nums`.",
      "",
      "If `target` exists, then return its index. Otherwise, return `-1`.",
      "",
      "You must write an algorithm with **O(log n)** runtime complexity."
    ].join("\n"),
    input: "An integer array nums on the first line (e.g. [-1,0,3,5,9,12]) and a target integer on the second line (e.g. 9).",
    output: "An integer representing the 0-indexed position of the target if found, or -1 if target is not in the array.",
    explanation: "target = 9 is at index 4 in [-1,0,3,5,9,12].",
    constraints: [
      "1 <= nums.length <= 10^4",
      "-10^4 < nums[i], target < 10^4",
      "All integers in nums are unique.",
      "nums is sorted in ascending order."
    ].join("\n"),
    hints: "Use a two-pointer approach tracking left and right boundaries, and search the middle element to divide the search space in half.",
    editorial: [
      "Binary Search is a classic divide-and-conquer search algorithm.",
      "By calculating the mid-point `mid = left + (right - left) / 2` and comparing it to the target, we can instantly discard half of the array at each iteration, resulting in O(log N) worst-case time complexity."
    ].join("\n"),
    testCases: [
      {
        input: "[-1,0,3,5,9,12]\n9",
        expectedOutput: "4",
        isSample: true,
        isHidden: false,
        explanation: "9 exists in nums and its index is 4.",
        order: 0,
      },
      {
        input: "[-1,0,3,5,9,12]\n2",
        expectedOutput: "-1",
        isSample: true,
        isHidden: false,
        explanation: "2 does not exist in nums, so we return -1.",
        order: 1,
      },
      {
        input: "[5]\n5",
        expectedOutput: "0",
        isSample: false,
        isHidden: true,
        explanation: "Array of size 1 containing the target at index 0.",
        order: 2,
      }
    ],
    codeSnippets: [
      {
        language: Language.CPP,
        code: [
          "#include <vector>",
          "",
          "class Solution {",
          "public:",
          "    int search(std::vector<int>& nums, int target) {",
          "        // Write your Binary Search implementation here",
          "        ",
          "    }",
          "};"
        ].join("\n"),
      },
      {
        language: Language.JAVASCRIPT,
        code: [
          "/**",
          " * @param {number[]} nums",
          " * @param {number} target",
          " * @return {number}",
          " */",
          "function solve(nums, target) {",
          "  // Write your Binary Search implementation here",
          "  ",
          "}"
        ].join("\n"),
      },
      {
        language: Language.PYTHON,
        code: [
          "from typing import List",
          "",
          "def solve(nums: List[int], target: int) -> int:",
          "    # Write your Binary Search implementation here",
          "    pass"
        ].join("\n"),
      },
      {
        language: Language.JAVA,
        code: [
          "import java.util.*;",
          "",
          "class Solution {",
          "    public int search(int[] nums, int target) {",
          "        // Write your Binary Search implementation here",
          "        ",
          "    }",
          "}"
        ].join("\n"),
      }
    ],
    solutions: [
      {
        language: Language.CPP,
        code: [
          "#include <iostream>",
          "#include <vector>",
          "#include <string>",
          "#include <sstream>",
          "",
          "class Solution {",
          "public:",
          "    int search(std::vector<int>& nums, int target) {",
          "        int left = 0, right = nums.size() - 1;",
          "        while (left <= right) {",
          "            int mid = left + (right - left) / 2;",
          "            if (nums[mid] == target) return mid;",
          "            if (nums[mid] < target) left = mid + 1;",
          "            else right = mid - 1;",
          "        }",
          "        return -1;",
          "    }",
          "};",
          "",
          "int main() {",
          "    std::string line;",
          "    if (std::getline(std::cin, line)) {",
          "        std::vector<int> nums;",
          "        std::string num_str = \"\";",
          "        for (char c : line) {",
          "            if (c == '[' || c == ']' || c == ' ' || c == '\\r' || c == '\\n') continue;",
          "            if (c == ',') {",
          "                if (!num_str.empty()) {",
          "                    nums.push_back(std::stoi(num_str));",
          "                    num_str = \"\";",
          "                }",
          "            } else {",
          "                num_str += c;",
          "            }",
          "        }",
          "        if (!num_str.empty()) {",
          "            nums.push_back(std::stoi(num_str));",
          "        }",
          "        int target;",
          "        if (std::cin >> target) {",
          "            Solution solver;",
          "            std::cout << solver.search(nums, target) << std::endl;",
          "        }",
          "    }",
          "    return 0;",
          "}"
        ].join("\n"),
      },
      {
        language: Language.JAVASCRIPT,
        code: [
          "const fs = require('fs');",
          "",
          "function solve(nums, target) {",
          "  let left = 0, right = nums.length - 1;",
          "  while (left <= right) {",
          "    const mid = Math.floor((left + right) / 2);",
          "    if (nums[mid] === target) return mid;",
          "    if (nums[mid] < target) left = mid + 1;",
          "    else right = mid - 1;",
          "  }",
          "  return -1;",
          "}",
          "",
          "const input = fs.readFileSync(0, 'utf-8').trim();",
          "if (input) {",
          "  const lines = input.split('\\n');",
          "  const nums = JSON.parse(lines[0].trim());",
          "  const target = parseInt(lines[1].trim(), 10);",
          "  console.log(solve(nums, target));",
          "}"
        ].join("\n"),
      },
      {
        language: Language.PYTHON,
        code: [
          "import sys",
          "import json",
          "",
          "def solve(nums, target):",
          "    left, right = 0, len(nums) - 1;",
          "    while left <= right:",
          "        mid = (left + right) // 2",
          "        if nums[mid] == target:",
          "            return mid",
          "        if nums[mid] < target:",
          "            left = mid + 1",
          "        else:",
          "            right = mid - 1",
          "    return -1",
          "",
          "input_data = sys.stdin.read().strip().split('\\n')",
          "if len(input_data) >= 2:",
          "    nums = json.loads(input_data[0].strip())",
          "    target = int(input_data[1].strip())",
          "    print(solve(nums, target))"
        ].join("\n"),
      },
      {
        language: Language.JAVA,
        code: [
          "import java.util.*;",
          "",
          "class Solution {",
          "    public int search(int[] nums, int target) {",
          "        int left = 0, right = nums.length - 1;",
          "        while (left <= right) {",
          "            int mid = left + (right - left) / 2;",
          "            if (nums[mid] == target) return mid;",
          "            if (nums[mid] < target) left = mid + 1;",
          "            else right = mid - 1;",
          "        }",
          "        return -1;",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Scanner sc = new Scanner(System.in);",
          "        if (sc.hasNextLine()) {",
          "            String line = sc.nextLine().trim();",
          "            line = line.replace(\"[\", \"\").replace(\"]\", \"\").replace(\" \", \"\");",
          "            String[] parts = line.split(\",\");",
          "            int[] nums = new int[parts.length];",
          "            for (int i = 0; i < parts.length; i++) {",
          "                nums[i] = Integer.parseInt(parts[i]);",
          "            }",
          "            if (sc.hasNextInt()) {",
          "                int target = sc.nextInt();",
          "                Solution solver = new Solution();",
          "                System.out.println(solver.search(nums, target));",
          "            }",
          "        }",
          "        sc.close();",
          "    }",
          "}"
        ].join("\n"),
      }
    ],
  },
  "palindrome": {
    title: "Palindrome",
    difficulty: Difficulty.EASY,
    tags: ["strings", "two-pointers"],
    description: [
      "A phrase is a **palindrome** if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward.",
      "",
      "Given a string `s`, return `true` if it is a palindrome, or `false` otherwise."
    ].join("\n"),
    input: "A single JSON-formatted string on the first line (e.g. \"A man, a plan, a canal: Panama\").",
    output: "A boolean string (\"true\" or \"false\") representing if the string is a palindrome.",
    explanation: "\"amanaplanacanalpanama\" is a palindrome.",
    constraints: [
      "1 <= s.length <= 2 * 10^5",
      "s consists only of printable ASCII characters."
    ].join("\n"),
    hints: "Clean the string to retain only lowercase characters and digits, and then inspect matching characters using a two-pointer approach.",
    editorial: "Using two pointers on a cleaned string allows palindrome validation in O(N) time complexity with O(1) auxiliary space.",
    testCases: [
      {
        input: "\"A man, a plan, a canal: Panama\"",
        expectedOutput: "true",
        isSample: true,
        isHidden: false,
        explanation: "\"amanaplanacanalpanama\" reads the same forward and backward.",
        order: 0,
      },
      {
        input: "\"race a car\"",
        expectedOutput: "false",
        isSample: true,
        isHidden: false,
        explanation: "\"raceacar\" is not a palindrome.",
        order: 1,
      }
    ],
    codeSnippets: [
      {
        language: Language.CPP,
        code: [
          "#include <string>",
          "",
          "class Solution {",
          "public:",
          "    bool isPalindrome(std::string s) {",
          "        // Write your Palindrome implementation here",
          "        ",
          "    }",
          "};"
        ].join("\n"),
      },
      {
        language: Language.JAVASCRIPT,
        code: [
          "/**",
          " * @param {string} s",
          " * @return {boolean}",
          " */",
          "function solve(s) {",
          "  // Write your Palindrome implementation here",
          "  ",
          "}"
        ].join("\n"),
      },
      {
        language: Language.PYTHON,
        code: [
          "def solve(s: str) -> bool:",
          "    # Write your Palindrome implementation here",
          "    pass"
        ].join("\n"),
      },
      {
        language: Language.JAVA,
        code: [
          "class Solution {",
          "    public boolean isPalindrome(String s) {",
          "        // Write your Palindrome implementation here",
          "        ",
          "    }",
          "}"
        ].join("\n"),
      }
    ],
    solutions: [
      {
        language: Language.CPP,
        code: [
          "#include <iostream>",
          "#include <string>",
          "#include <cctype>",
          "",
          "class Solution {",
          "public:",
          "    bool isPalindrome(std::string s) {",
          "        int left = 0, right = s.length() - 1;",
          "        while (left < right) {",
          "            while (left < right && !std::isalnum(s[left])) left++;",
          "            while (left < right && !std::isalnum(s[right])) right--;",
          "            if (std::tolower(s[left]) != std::tolower(s[right])) return false;",
          "            left++;",
          "            right--;",
          "        }",
          "        return true;",
          "    }",
          "};",
          "",
          "int main() {",
          "    std::string line;",
          "    if (std::getline(std::cin, line)) {",
          "        if (line.size() >= 2 && line.front() == '\"' && line.back() == '\"') {",
          "            line = line.substr(1, line.size() - 2);",
          "        }",
          "        Solution solver;",
          "        std::cout << (solver.isPalindrome(line) ? \"true\" : \"false\") << std::endl;",
          "    }",
          "    return 0;",
          "}"
        ].join("\n"),
      },
      {
        language: Language.JAVASCRIPT,
        code: [
          "const fs = require('fs');",
          "",
          "function solve(s) {",
          "  const cleaned = s.toLowerCase().replace(/[^a-z0-9]/g, '');",
          "  let left = 0, right = cleaned.length - 1;",
          "  while (left < right) {",
          "    if (cleaned[left] !== cleaned[right]) return false;",
          "    left++;",
          "    right--;",
          "  }",
          "  return true;",
          "}",
          "",
          "let input = fs.readFileSync(0, 'utf-8').trim();",
          "if (input) {",
          "  if (input.startsWith('\"') && input.endsWith('\"')) {",
          "    try {",
          "      input = JSON.parse(input);",
          "    } catch (e) {",
          "      input = input.slice(1, -1);",
          "    }",
          "  }",
          "  console.log(solve(input) ? \"true\" : \"false\");",
          "}"
        ].join("\n"),
      },
      {
        language: Language.PYTHON,
        code: [
          "import sys",
          "import json",
          "",
          "def solve(s):",
          "    cleaned = \"\".join(c.lower() for c in s if c.isalnum())",
          "    return cleaned == cleaned[::-1]",
          "",
          "input_data = sys.stdin.read().strip()",
          "if input_data:",
          "    if input_data.startswith('\"') and input_data.endswith('\"'):",
          "        try:",
          "            s = json.loads(input_data)",
          "        except:",
          "            s = input_data[1:-1]",
          "    else:",
          "        s = input_data",
          "    print(\"true\" if solve(s) else \"false\")"
        ].join("\n"),
      },
      {
        language: Language.JAVA,
        code: [
          "import java.util.*;",
          "",
          "class Solution {",
          "    public boolean isPalindrome(String s) {",
          "        int left = 0, right = s.length() - 1;",
          "        while (left < right) {",
          "            while (left < right && !Character.isLetterOrDigit(s.charAt(left))) left++;",
          "            while (left < right && !Character.isLetterOrDigit(s.charAt(right))) right--;",
          "            if (Character.toLowerCase(s.charAt(left)) != Character.toLowerCase(s.charAt(right))) {",
          "                return false;",
          "            }",
          "            left++;",
          "            right--;",
          "        }",
          "        return true;",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Scanner sc = new Scanner(System.in);",
          "        if (sc.hasNextLine()) {",
          "            String line = sc.nextLine().trim();",
          "            if (line.startsWith(\"\\\"\") && line.endsWith(\"\\\"\")) {",
          "                line = line.substring(1, line.length() - 1);",
          "            }",
          "            Solution solver = new Solution();",
          "            System.out.println(solver.isPalindrome(line) ? \"true\" : \"false\");",
          "        }",
          "        sc.close();",
          "    }",
          "}"
        ].join("\n"),
      }
    ],
  },
  "merge-sort": {
    title: "Merge Sort",
    difficulty: Difficulty.MEDIUM,
    tags: ["sorting", "divide-and-conquer", "algorithms"],
    description: [
      "Given an array of integers `nums`, sort the array in ascending order and return it.",
      "",
      "You must solve the problem without using any built-in library sort functions, and ideally with **O(n log n)** runtime complexity using the Merge Sort algorithm."
    ].join("\n"),
    input: "An integer array nums on the first line (e.g. [5,2,3,1]).",
    output: "The sorted integer array printed in JSON format (e.g. [1,2,3,5]).",
    explanation: "Nums array [5,2,3,1] sorted is [1,2,3,5].",
    constraints: [
      "1 <= nums.length <= 5 * 10^4",
      "-5 * 10^4 <= nums[i] <= 5 * 10^4"
    ].join("\n"),
    hints: "Implement standard divide-and-conquer merge sort: slice the array in two halves recursively, sort each half, and merge them back together in linear time.",
    editorial: "Merge Sort maintains O(N log N) worst-case time complexity, dividing array inputs recursively and utilizing O(N) auxiliary space during slice merges.",
    testCases: [
      {
        input: "[5,2,3,1]",
        expectedOutput: "[1,2,3,5]",
        isSample: true,
        isHidden: false,
        explanation: "Standard sorting array values in ascending order.",
        order: 0,
      },
      {
        input: "[5,1,1,2,0,0]",
        expectedOutput: "[0,0,1,1,2,5]",
        isSample: true,
        isHidden: false,
        explanation: "Handling duplicate integer values safely.",
        order: 1,
      }
    ],
    codeSnippets: [
      {
        language: Language.CPP,
        code: [
          "#include <vector>",
          "",
          "class Solution {",
          "public:",
          "    std::vector<int> sortArray(std::vector<int>& nums) {",
          "        // Write your Merge Sort implementation here",
          "        ",
          "    }",
          "};"
        ].join("\n"),
      },
      {
        language: Language.JAVASCRIPT,
        code: [
          "/**",
          " * @param {number[]} nums",
          " * @return {number[]}",
          " */",
          "function solve(nums) {",
          "  // Write your Merge Sort implementation here",
          "  ",
          "}"
        ].join("\n"),
      },
      {
        language: Language.PYTHON,
        code: [
          "from typing import List",
          "",
          "def solve(nums: List[int]) -> List[int]:",
          "    # Write your Merge Sort implementation here",
          "    pass"
        ].join("\n"),
      },
      {
        language: Language.JAVA,
        code: [
          "import java.util.*;",
          "",
          "class Solution {",
          "    public int[] sortArray(int[] nums) {",
          "        // Write your Merge Sort implementation here",
          "        ",
          "    }",
          "}"
        ].join("\n"),
      }
    ],
    solutions: [
      {
        language: Language.CPP,
        code: [
          "#include <iostream>",
          "#include <vector>",
          "#include <string>",
          "",
          "class Solution {",
          "private:",
          "    void merge(std::vector<int>& nums, int left, int mid, int right) {",
          "        int n1 = mid - left + 1;",
          "        int n2 = right - mid;",
          "        std::vector<int> L(n1), R(n2);",
          "        for (int i = 0; i < n1; i++) L[i] = nums[left + i];",
          "        for (int j = 0; j < n2; j++) R[j] = nums[mid + 1 + j];",
          "        int i = 0, j = 0, k = left;",
          "        while (i < n1 && j < n2) {",
          "            if (L[i] <= R[j]) {",
          "                nums[k] = L[i];",
          "                i++;",
          "            } else {",
          "                nums[k] = R[j];",
          "                j++;",
          "            }",
          "            k++;",
          "        }",
          "        while (i < n1) {",
          "            nums[k] = L[i];",
          "            i++;",
          "            k++;",
          "        }",
          "        while (j < n2) {",
          "            nums[k] = R[j];",
          "            j++;",
          "            k++;",
          "        }",
          "    }",
          "    void mergeSort(std::vector<int>& nums, int left, int right) {",
          "        if (left < right) {",
          "            int mid = left + (right - left) / 2;",
          "            mergeSort(nums, left, mid);",
          "            mergeSort(nums, mid + 1, right);",
          "            merge(nums, left, mid, right);",
          "        }",
          "    }",
          "public:",
          "    std::vector<int> sortArray(std::vector<int>& nums) {",
          "        if (nums.empty()) return nums;",
          "        mergeSort(nums, 0, nums.size() - 1);",
          "        return nums;",
          "    }",
          "};",
          "",
          "int main() {",
          "    std::string line;",
          "    if (std::getline(std::cin, line)) {",
          "        std::vector<int> nums;",
          "        std::string num_str = \"\";",
          "        for (char c : line) {",
          "            if (c == '[' || c == ']' || c == ' ' || c == '\\r' || c == '\\n') continue;",
          "            if (c == ',') {",
          "                if (!num_str.empty()) {",
          "                    nums.push_back(std::stoi(num_str));",
          "                    num_str = \"\";",
          "                }",
          "            } else {",
          "                num_str += c;",
          "            }",
          "        }",
          "        if (!num_str.empty()) {",
          "            nums.push_back(std::stoi(num_str));",
          "        }",
          "        Solution solver;",
          "        std::vector<int> result = solver.sortArray(nums);",
          "        std::cout << \"[\";",
          "        for (size_t i = 0; i < result.size(); i++) {",
          "            std::cout << result[i] << (i + 1 < result.size() ? \",\" : \"\");",
          "        }",
          "        std::cout << \"]\" << std::endl;",
          "    }",
          "    return 0;",
          "}"
        ].join("\n"),
      },
      {
        language: Language.JAVASCRIPT,
        code: [
          "const fs = require('fs');",
          "",
          "function merge(leftArr, rightArr) {",
          "  const res = [];",
          "  let l = 0, r = 0;",
          "  while (l < leftArr.length && r < rightArr.length) {",
          "    if (leftArr[l] <= rightArr[r]) {",
          "      res.push(leftArr[l]);",
          "      l++;",
          "    } else {",
          "      res.push(rightArr[r]);",
          "      r++;",
          "    }",
          "  }",
          "  return res.concat(leftArr.slice(l)).concat(rightArr.slice(r));",
          "}",
          "",
          "function mergeSort(arr) {",
          "  if (arr.length <= 1) return arr;",
          "  const mid = Math.floor(arr.length / 2);",
          "  const left = mergeSort(arr.slice(0, mid));",
          "  const right = mergeSort(arr.slice(mid));",
          "  return merge(left, right);",
          "}",
          "",
          "const input = fs.readFileSync(0, 'utf-8').trim();",
          "if (input) {",
          "  const arr = JSON.parse(input);",
          "  console.log(JSON.stringify(mergeSort(arr)));",
          "}"
        ].join("\n"),
      },
      {
        language: Language.PYTHON,
        code: [
          "import sys",
          "import json",
          "",
          "def merge_sort(arr):",
          "    if len(arr) <= 1:",
          "        return arr",
          "    mid = len(arr) // 2",
          "    left = merge_sort(arr[:mid])",
          "    right = merge_sort(arr[mid:])",
          "    res = []",
          "    l = r = 0",
          "    while l < len(left) and r < len(right):",
          "        if left[l] <= right[r]:",
          "            res.append(left[l])",
          "            l += 1",
          "        else:",
          "            res.append(right[r])",
          "            r += 1",
          "    res.extend(left[l:])",
          "    res.extend(right[r:])",
          "    return res",
          "",
          "input_data = sys.stdin.read().strip()",
          "if input_data:",
          "    arr = json.loads(input_data)",
          "    print(json.dumps(merge_sort(arr), separators=(',', ':')))"
        ].join("\n"),
      },
      {
        language: Language.JAVA,
        code: [
          "import java.util.*;",
          "",
          "class Solution {",
          "    private void merge(int[] arr, int l, int m, int r) {",
          "        int n1 = m - l + 1;",
          "        int n2 = r - m;",
          "        int[] L = new int[n1];",
          "        int[] R = new int[n2];",
          "        for (int i = 0; i < n1; ++i) L[i] = arr[l + i];",
          "        for (int j = 0; j < n2; ++j) R[j] = arr[m + 1 + j];",
          "        int i = 0, j = 0, k = l;",
          "        while (i < n1 && j < n2) {",
          "            if (L[i] <= R[j]) {",
          "                arr[k] = L[i];",
          "                i++;",
          "            } else {",
          "                arr[k] = R[j];",
          "                j++;",
          "            }",
          "            k++;",
          "        }",
          "        while (i < n1) {",
          "            arr[k] = L[i];",
          "            i++;",
          "            k++;",
          "        }",
          "        while (j < n2) {",
          "            arr[k] = R[j];",
          "            j++;",
          "            k++;",
          "        }",
          "    }",
          "    private void sort(int[] arr, int l, int r) {",
          "        if (l < r) {",
          "            int m = l + (r - l) / 2;",
          "            sort(arr, l, m);",
          "            sort(arr, m + 1, r);",
          "            merge(arr, l, m, r);",
          "        }",
          "    }",
          "    public int[] sortArray(int[] nums) {",
          "        sort(nums, 0, nums.length - 1);",
          "        return nums;",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Scanner sc = new Scanner(System.in);",
          "        if (sc.hasNextLine()) {",
          "            String line = sc.nextLine().trim();",
          "            line = line.replace(\"[\", \"\").replace(\"]\", \"\").replace(\" \", \"\");",
          "            if (line.isEmpty()) {",
          "                System.out.println(\"[]\");",
          "                sc.close();",
          "                return;",
          "            }",
          "            String[] parts = line.split(\",\");",
          "            int[] nums = new int[parts.length];",
          "            for (int i = 0; i < parts.length; i++) {",
          "                nums[i] = Integer.parseInt(parts[i]);",
          "            }",
          "            Solution solver = new Solution();",
          "            int[] sorted = solver.sortArray(nums);",
          "            System.out.print(\"[\");",
          "            for (int i = 0; i < sorted.length; i++) {",
          "                System.out.print(sorted[i] + (i + 1 < sorted.length ? \",\" : \"\"));",
          "            }",
          "            System.out.println(\"]\");",
          "        }",
          "        sc.close();",
          "    }",
          "}"
        ].join("\n"),
      }
    ],
  },
  "house-robber": {
    title: "House Robber",
    difficulty: Difficulty.MEDIUM,
    tags: ["dynamic-programming", "algorithms"],
    description: [
      "You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security systems connected and **it will automatically contact the police if two adjacent houses were broken into on the same night**.",
      "",
      "Given an integer array `nums` representing the amount of money of each house, return *the maximum amount of money you can rob tonight without alerting the police*."
    ].join("\n"),
    input: "An integer array nums on the first line (e.g. [1,2,3,1]).",
    output: "An integer representing the maximum stashed cash that can be robbed.",
    explanation: "Rob house 1 (money = 1) and then rob house 3 (money = 3). Total = 4.",
    constraints: [
      "1 <= nums.length <= 400",
      "0 <= nums[i] <= 400"
    ].join("\n"),
    hints: "Use dynamic programming. Maintain a running maximum cash robbed up to the current house: `dp[i] = max(dp[i-1], dp[i-2] + nums[i])`.",
    editorial: "House Robber resolves into a standard 1D Dynamic Programming structure, solvable in O(N) time complexity and optimized down to O(1) space complexity by storing only the previous two house values.",
    testCases: [
      {
        input: "[1,2,3,1]",
        expectedOutput: "4",
        isSample: true,
        isHidden: false,
        explanation: "Maximum money is 1 + 3 = 4.",
        order: 0,
      },
      {
        input: "[2,7,9,3,1]",
        expectedOutput: "12",
        isSample: true,
        isHidden: false,
        explanation: "Maximum money is 2 + 9 + 1 = 12.",
        order: 1,
      }
    ],
    codeSnippets: [
      {
        language: Language.CPP,
        code: [
          "#include <vector>",
          "",
          "class Solution {",
          "public:",
          "    int rob(std::vector<int>& nums) {",
          "        // Write your House Robber implementation here",
          "        ",
          "    }",
          "};"
        ].join("\n"),
      },
      {
        language: Language.JAVASCRIPT,
        code: [
          "/**",
          " * @param {number[]} nums",
          " * @return {number}",
          " */",
          "function solve(nums) {",
          "  // Write your House Robber implementation here",
          "  ",
          "}"
        ].join("\n"),
      },
      {
        language: Language.PYTHON,
        code: [
          "from typing import List",
          "",
          "def solve(nums: List[int]) -> int:",
          "    # Write your House Robber implementation here",
          "    pass"
        ].join("\n"),
      },
      {
        language: Language.JAVA,
        code: [
          "class Solution {",
          "    public int rob(int[] nums) {",
          "        // Write your House Robber implementation here",
          "        ",
          "    }",
          "}"
        ].join("\n"),
      }
    ],
    solutions: [
      {
        language: Language.CPP,
        code: [
          "#include <iostream>",
          "#include <vector>",
          "#include <string>",
          "#include <algorithm>",
          "",
          "class Solution {",
          "public:",
          "    int rob(std::vector<int>& nums) {",
          "        if (nums.empty()) return 0;",
          "        if (nums.size() == 1) return nums[0];",
          "        int prev2 = 0;",
          "        int prev1 = 0;",
          "        for (int num : nums) {",
          "            int current = std::max(prev1, prev2 + num);",
          "            prev2 = prev1;",
          "            prev1 = current;",
          "        }",
          "        return prev1;",
          "    }",
          "};",
          "",
          "int main() {",
          "    std::string line;",
          "    if (std::getline(std::cin, line)) {",
          "        std::vector<int> nums;",
          "        std::string num_str = \"\";",
          "        for (char c : line) {",
          "            if (c == '[' || c == ']' || c == ' ' || c == '\\r' || c == '\\n') continue;",
          "            if (c == ',') {",
          "                if (!num_str.empty()) {",
          "                    nums.push_back(std::stoi(num_str));",
          "                    num_str = \"\";",
          "                }",
          "            } else {",
          "                num_str += c;",
          "            }",
          "        }",
          "        if (!num_str.empty()) {",
          "            nums.push_back(std::stoi(num_str));",
          "        }",
          "        Solution solver;",
          "        std::cout << solver.rob(nums) << std::endl;",
          "    }",
          "    return 0;",
          "}"
        ].join("\n"),
      },
      {
        language: Language.JAVASCRIPT,
        code: [
          "const fs = require('fs');",
          "",
          "function solve(nums) {",
          "  if (nums.length === 0) return 0;",
          "  let prev2 = 0, prev1 = 0;",
          "  for (const num of nums) {",
          "    const current = Math.max(prev1, prev2 + num);",
          "    prev2 = prev1;",
          "    prev1 = current;",
          "  }",
          "  return prev1;",
          "}",
          "",
          "const input = fs.readFileSync(0, 'utf-8').trim();",
          "if (input) {",
          "  const nums = JSON.parse(input);",
          "  console.log(solve(nums));",
          "}"
        ].join("\n"),
      },
      {
        language: Language.PYTHON,
        code: [
          "import sys",
          "import json",
          "",
          "def solve(nums):",
          "    if not nums:",
          "        return 0",
          "    prev2 = prev1 = 0",
          "    for num in nums:",
          "        prev2, prev1 = prev1, max(prev1, prev2 + num)",
          "    return prev1",
          "",
          "input_data = sys.stdin.read().strip()",
          "if input_data:",
          "    nums = json.loads(input_data)",
          "    print(solve(nums))"
        ].join("\n"),
      },
      {
        language: Language.JAVA,
        code: [
          "import java.util.*;",
          "",
          "class Solution {",
          "    public int rob(int[] nums) {",
          "        if (nums.length == 0) return 0;",
          "        int prev2 = 0, prev1 = 0;",
          "        for (int num : nums) {",
          "            int current = Math.max(prev1, prev2 + num);",
          "            prev2 = prev1;",
          "            prev1 = current;",
          "        }",
          "        return prev1;",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Scanner sc = new Scanner(System.in);",
          "        if (sc.hasNextLine()) {",
          "            String line = sc.nextLine().trim();",
          "            line = line.replace(\"[\", \"\").replace(\"]\", \"\").replace(\" \", \"\");",
          "            if (line.isEmpty()) {",
          "                System.out.println(0);",
          "                sc.close();",
          "                return;",
          "            }",
          "            String[] parts = line.split(\",\");",
          "            int[] nums = new int[parts.length];",
          "            for (int i = 0; i < parts.length; i++) {",
          "                nums[i] = Integer.parseInt(parts[i]);",
          "            }",
          "            Solution solver = new Solution();",
          "            System.out.println(solver.rob(nums));",
          "        }",
          "        sc.close();",
          "    }",
          "}"
        ].join("\n"),
      }
    ],
  },
  "reverse-linked-list": {
    title: "Reverse a Linked List",
    difficulty: Difficulty.EASY,
    tags: ["linked-list", "data-structures"],
    description: [
      "Given the `head` of a singly linked list, reverse the list, and return *the reversed list*.",
      "",
      "The list elements will be represented as a JSON array of integers for standard execution formats."
    ].join("\n"),
    input: "An integer array representing the elements of the linked list on the first line (e.g. [1,2,3,4,5]).",
    output: "An integer array representing the reversed linked list in JSON format (e.g. [5,4,3,2,1]).",
    explanation: "Input [1,2,3,4,5] yields reversed [5,4,3,2,1].",
    constraints: [
      "The number of nodes in the list is in the range [0, 5000].",
      "-5000 <= Node.val <= 5000"
    ].join("\n"),
    hints: "Initialize a 'prev' pointer as null and a 'curr' pointer as the head. Swap next nodes iteratively as you traverse.",
    editorial: "Reversing a Linked List is solvable iteratively in O(N) time complexity and O(1) space complexity by swapping current pointer connections inline.",
    testCases: [
      {
        input: "[1,2,3,4,5]",
        expectedOutput: "[5,4,3,2,1]",
        isSample: true,
        isHidden: false,
        explanation: "Reversing linked list standard node sequence.",
        order: 0,
      },
      {
        input: "[1,2]",
        expectedOutput: "[2,1]",
        isSample: true,
        isHidden: false,
        explanation: "Reversing linked list size 2.",
        order: 1,
      }
    ],
    codeSnippets: [
      {
        language: Language.CPP,
        code: [
          "/**",
          " * Definition for singly-linked list.",
          " * struct ListNode {",
          " *     int val;",
          " *     ListNode *next;",
          " *     ListNode(int x) : val(x), next(NULL) {}",
          " * };",
          " */",
          "class Solution {",
          "public:",
          "    ListNode* reverseList(ListNode* head) {",
          "        // Write your Reverse Linked List implementation here",
          "        ",
          "    }",
          "};"
        ].join("\n"),
      },
      {
        language: Language.JAVASCRIPT,
        code: [
          "/**",
          " * Definition for singly-linked list.",
          " * function ListNode(val, next) {",
          " *     this.val = (val===undefined ? 0 : val)",
          " *     this.next = (next===undefined ? null : next)",
          " * }",
          " */",
          "/**",
          " * @param {ListNode} head",
          " * @return {ListNode}",
          " */",
          "function solve(head) {",
          "  // Write your Reverse Linked List implementation here",
          "  ",
          "}"
        ].join("\n"),
      },
      {
        language: Language.PYTHON,
        code: [
          "# Definition for singly-linked list.",
          "# class ListNode:",
          "#     def __init__(self, val=0, next=None):",
          "#         self.val = val",
          "#         self.next = next",
          "",
          "def solve(head: ListNode) -> ListNode:",
          "    # Write your Reverse Linked List implementation here",
          "    pass"
        ].join("\n"),
      },
      {
        language: Language.JAVA,
        code: [
          "/**",
          " * Definition for singly-linked list.",
          " * public class ListNode {",
          " *     int val;",
          " *     ListNode next;",
          " *     ListNode(int x) { val = x; next = null; }",
          " * }",
          " */",
          "class Solution {",
          "    public ListNode reverseList(ListNode head) {",
          "        // Write your Reverse Linked List implementation here",
          "        ",
          "    }",
          "}"
        ].join("\n"),
      }
    ],
    solutions: [
      {
        language: Language.CPP,
        code: [
          "#include <iostream>",
          "#include <vector>",
          "#include <string>",
          "",
          "struct ListNode {",
          "    int val;",
          "    ListNode* next;",
          "    ListNode(int x) : val(x), next(NULL) {}",
          "};",
          "",
          "class Solution {",
          "public:",
          "    ListNode* reverseList(ListNode* head) {",
          "        ListNode* prev = NULL;",
          "        ListNode* curr = head;",
          "        while (curr != NULL) {",
          "            ListNode* nextTemp = curr->next;",
          "            curr->next = prev;",
          "            prev = curr;",
          "            curr = nextTemp;",
          "        }",
          "        return prev;",
          "    }",
          "};",
          "",
          "int main() {",
          "    std::string line;",
          "    if (std::getline(std::cin, line)) {",
          "        std::vector<int> nums;",
          "        std::string num_str = \"\";",
          "        for (char c : line) {",
          "            if (c == '[' || c == ']' || c == ' ' || c == '\\r' || c == '\\n') continue;",
          "            if (c == ',') {",
          "                if (!num_str.empty()) {",
          "                    nums.push_back(std::stoi(num_str));",
          "                    num_str = \"\";",
          "                }",
          "            } else {",
          "                num_str += c;",
          "            }",
          "        }",
          "        if (!num_str.empty()) {",
          "            nums.push_back(std::stoi(num_str));",
          "        }",
          "        ListNode* head = NULL;",
          "        ListNode* tail = NULL;",
          "        for (int num : nums) {",
          "            ListNode* node = new ListNode(num);",
          "            if (head == NULL) {",
          "                head = node;",
          "                tail = node;",
          "            } else {",
          "                tail->next = node;",
          "                tail = node;",
          "            }",
          "        }",
          "        Solution solver;",
          "        ListNode* reversed = solver.reverseList(head);",
          "        std::cout << \"[\";",
          "        ListNode* curr = reversed;",
          "        while (curr != NULL) {",
          "            std::cout << curr->val << (curr->next != NULL ? \",\" : \"\");",
          "            curr = curr->next;",
          "        }",
          "        std::cout << \"]\" << std::endl;",
          "    }",
          "    return 0;",
          "}"
        ].join("\n"),
      },
      {
        language: Language.JAVASCRIPT,
        code: [
          "const fs = require('fs');",
          "",
          "class ListNode {",
          "  constructor(val = 0, next = null) {",
          "    this.val = val;",
          "    this.next = next;",
          "  }",
          "}",
          "",
          "function reverseList(head) {",
          "  let prev = null;",
          "  let curr = head;",
          "  while (curr !== null) {",
          "    const nextTemp = curr.next;",
          "    curr.next = prev;",
          "    prev = curr;",
          "    curr = nextTemp;",
          "  }",
          "  return prev;",
          "}",
          "",
          "const input = fs.readFileSync(0, 'utf-8').trim();",
          "if (input) {",
          "  const nums = JSON.parse(input);",
          "  let head = null;",
          "  let tail = null;",
          "  for (const num of nums) {",
          "    const node = new ListNode(num);",
          "    if (head === null) {",
          "      head = node;",
          "      tail = node;",
          "    } else {",
          "      tail.next = node;",
          "      tail = node;",
          "    }",
          "  }",
          "  const reversed = reverseList(head);",
          "  const result = [];",
          "  let curr = reversed;",
          "  while (curr !== null) {",
          "    result.push(curr.val);",
          "    curr = curr.next;",
          "  }",
          "  console.log(JSON.stringify(result));",
          "}"
        ].join("\n"),
      },
      {
        language: Language.PYTHON,
        code: [
          "import sys",
          "import json",
          "",
          "class ListNode:",
          "    def __init__(self, val=0, next=None):",
          "        self.val = val",
          "        self.next = next",
          "",
          "def reverseList(head: ListNode) -> ListNode:",
          "    prev = None",
          "    curr = head",
          "    while curr is not None:",
          "        nextTemp = curr.next",
          "        curr.next = prev",
          "        prev = curr",
          "        curr = nextTemp",
          "    return prev",
          "",
          "input_data = sys.stdin.read().strip()",
          "if input_data:",
          "    nums = json.loads(input_data)",
          "    head = None",
          "    tail = None",
          "    for num in nums:",
          "        node = ListNode(num)",
          "        if head is None:",
          "            head = node",
          "            tail = node",
          "        else:",
          "            tail.next = node",
          "            tail = node",
          "    reversed_head = reverseList(head)",
          "    result = []",
          "    curr = reversed_head",
          "    while curr is not None:",
          "        result.append(curr.val)",
          "        curr = curr.next",
          "    print(json.dumps(result, separators=(',', ':')))"
        ].join("\n"),
      },
      {
        language: Language.JAVA,
        code: [
          "import java.util.*;",
          "",
          "class ListNode {",
          "    int val;",
          "    ListNode next;",
          "    ListNode(int x) { val = x; next = null; }",
          "}",
          "",
          "class Solution {",
          "    public ListNode reverseList(ListNode head) {",
          "        ListNode prev = null;",
          "        ListNode curr = head;",
          "        while (curr != null) {",
          "            ListNode nextTemp = curr.next;",
          "            curr.next = prev;",
          "            prev = curr;",
          "            curr = nextTemp;",
          "        }",
          "        return prev;",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Scanner sc = new Scanner(System.in);",
          "        if (sc.hasNextLine()) {",
          "            String line = sc.nextLine().trim();",
          "            line = line.replace(\"[\", \"\").replace(\"]\", \"\").replace(\" \", \"\");",
          "            if (line.isEmpty()) {",
          "                System.out.println(\"[]\");",
          "                sc.close();",
          "                return;",
          "            }",
          "            String[] parts = line.split(\",\");",
          "            ListNode head = null;",
          "            ListNode tail = null;",
          "            for (String part : parts) {",
          "                ListNode node = new ListNode(Integer.parseInt(part));",
          "                if (head == null) {",
          "                    head = node;",
          "                    tail = node;",
          "                } else {",
          "                    tail.next = node;",
          "                    tail = node;",
          "                }",
          "            }",
          "            Solution solver = new Solution();",
          "            ListNode reversed = solver.reverseList(head);",
          "            System.out.print(\"[\");",
          "            ListNode curr = reversed;",
          "            while (curr != null) {",
          "                System.out.print(curr.val + (curr.next != null ? \",\" : \"\"));",
          "                curr = curr.next;",
          "            }",
          "            System.out.println(\"]\");",
          "        }",
          "        sc.close();",
          "    }",
          "}"
        ].join("\n"),
      }
    ],
  }
};

export const emptyDefaultValues = {
  title: "",
  difficulty: Difficulty.EASY,
  tags: [] as string[],
  description: "",
  input: "",
  output: "",
  explanation: "",
  constraints: "",
  hints: "",
  editorial: "",
  testCases: [
    {
      input: "",
      expectedOutput: "",
      isSample: true,
      isHidden: false,
      explanation: "",
      order: 0,
    },
  ],
  codeSnippets: [
    {
      language: Language.CPP,
      code: [
        "#include <vector>",
        "",
        "class Solution {",
        "public:",
        "    // Write code boilerplate here",
        "    ",
        "};"
      ].join("\n"),
    },
  ],
  solutions: [
    {
      language: Language.CPP,
      code: "",
    },
  ],
};

// Automatic lookup helper for when a user changes language selectors
export function getSampleTemplate(
  title: string,
  language: Language,
  type: "starter" | "solution"
): string {
  const sample = Object.values(SAMPLE_PROBLEMS).find(
    (p) => p.title.toLowerCase() === title.toLowerCase()
  );
  if (sample) {
    if (type === "starter") {
      return sample.codeSnippets.find((s) => s.language === language)?.code || "";
    } else {
      return sample.solutions.find((s) => s.language === language)?.code || "";
    }
  }
  // Standard defaults if custom
  if (type === "starter") {
    if (language === Language.CPP) {
      return "#include <vector>\n\nclass Solution {\npublic:\n    \n};";
    } else if (language === Language.JAVASCRIPT) {
      return "function solve() {\n  \n}";
    } else if (language === Language.PYTHON) {
      return "def solve():\n    pass";
    } else if (language === Language.JAVA) {
      return "import java.util.*;\n\nclass Solution {\n    \n}";
    }
  }
  return "";
}
