import { Language } from "@/generated/prisma";

export const SUPPORTED_LANGUAGES = [
  Language.CPP,
  Language.JAVASCRIPT,
  Language.PYTHON,
  Language.JAVA,
];

// Reusable Map for Starter Code Templates
export const STARTER_TEMPLATES: Record<Language, string> = {
  [Language.CPP]: [
    "#include <vector>",
    "",
    "class Solution {",
    "public:",
    "    std::vector<int> twoSum(std::vector<int>& nums, int target) {",
    "        // Write your C++ solution here",
    "        ",
    "    }",
    "};"
  ].join("\n"),

  [Language.JAVASCRIPT]: [
    "/**",
    " * @param {number[]} nums",
    " * @param {number} target",
    " * @return {number[]}",
    " */",
    "function solve(nums, target) {",
    "  // Write your JavaScript solution here",
    "  ",
    "}"
  ].join("\n"),

  [Language.PYTHON]: [
    "from typing import List",
    "",
    "def solve(nums: List[int], target: int) -> List[int]:",
    "    # Write your Python solution here",
    "    pass"
  ].join("\n"),

  [Language.JAVA]: [
    "import java.util.*;",
    "",
    "class Solution {",
    "    public int[] twoSum(int[] nums, int target) {",
    "        // Write your Java solution here",
    "        ",
    "    }",
    "}"
  ].join("\n"),
};

// Reusable Map for fully executable Reference Solutions validated in Judge0
export const SOLUTION_TEMPLATES: Record<Language, string> = {
  [Language.CPP]: [
    "#include <iostream>",
    "#include <vector>",
    "#include <unordered_map>",
    "#include <string>",
    "#include <sstream>",
    "",
    "class Solution {",
    "public:",
    "    std::vector<int> twoSum(std::vector<int>& nums, int target) {",
    "        std::unordered_map<int, int> seen;",
    "        for (int i = 0; i < nums.size(); ++i) {",
    "            int complement = target - nums[i];",
    "            if (seen.count(complement)) {",
    "                return {seen[complement], i};",
    "            }",
    "            seen[nums[i]] = i;",
    "        }",
    "        return {};",
    "    }",
    "};",
    "",
    "int main() {",
    "    std::string line;",
    "    if (std::getline(std::cin, line)) {",
    "        std::vector<int> nums;",
    "        std::string num_str = \"\";",
    "        for (char c : line) {",
    "            if (c == '[' || c == ']' || c == ' ' || c == '\\r' || c == '\\n') continue;",
    "            if (c == ',') {",
    "                if (!num_str.empty()) {",
    "                    nums.push_back(std::stoi(num_str));",
    "                    num_str = \"\";",
    "                }",
    "            } else {",
    "                num_str += c;",
    "            }",
    "        }",
    "        if (!num_str.empty()) {",
    "            nums.push_back(std::stoi(num_str));",
    "        }",
    "",
    "        int target;",
    "        if (std::cin >> target) {",
    "            Solution solver;",
    "            std::vector<int> result = solver.twoSum(nums, target);",
    "            if (result.size() == 2) {",
    "                std::cout << \"[\" << result[0] << \",\" << result[1] << \"]\" << std::endl;",
    "            } else {",
    "                std::cout << \"[]\" << std::endl;",
    "            }",
    "        }",
    "    }",
    "    return 0;",
    "}"
  ].join("\n"),

  [Language.JAVASCRIPT]: [
    "const fs = require('fs');",
    "",
    "function solve(nums, target) {",
    "  const map = new Map();",
    "  for (let i = 0; i < nums.length; i++) {",
    "    const complement = target - nums[i];",
    "    if (map.has(complement)) {",
    "      return [map.get(complement), i];",
    "    }",
    "    map.set(nums[i], i);",
    "  }",
    "  return [];",
    "}",
    "",
    "const input = fs.readFileSync(0, 'utf-8').trim();",
    "if (input) {",
    "  const lines = input.split('\\n');",
    "  const nums = JSON.parse(lines[0].trim());",
    "  const target = parseInt(lines[1].trim(), 10);",
    "  console.log(JSON.stringify(solve(nums, target)));",
    "}"
  ].join("\n"),

  [Language.PYTHON]: [
    "import sys",
    "import json",
    "",
    "def solve(nums, target):",
    "    seen = {}",
    "    for i, num in enumerate(nums):",
    "        complement = target - num",
    "        if complement in seen:",
    "            return [seen[complement], i]",
    "        seen[num] = i",
    "    return []",
    "",
    "input_data = sys.stdin.read().strip().split('\\n')",
    "if len(input_data) >= 2:",
    "    nums = json.loads(input_data[0].strip())",
    "    target = int(input_data[1].strip())",
    "    result = solve(nums, target)",
    "    print(json.dumps(result))"
  ].join("\n"),

  [Language.JAVA]: [
    "import java.util.*;",
    "",
    "class Solution {",
    "    public int[] twoSum(int[] nums, int target) {",
    "        Map<Integer, Integer> seen = new HashMap<>();",
    "        for (int i = 0; i < nums.length; ++i) {",
    "            int complement = target - nums[i];",
    "            if (seen.containsKey(complement)) {",
    "                return new int[] { seen.get(complement), i };",
    "            }",
    "            seen.put(nums[i], i);",
    "        }",
    "        return new int[0];",
    "    }",
    "}",
    "",
    "public class Main {",
    "    public static void main(String[] args) {",
    "        Scanner sc = new Scanner(System.in);",
    "        if (sc.hasNextLine()) {",
    "            String line = sc.nextLine().trim();",
    "            line = line.replace(\"[\", \"\").replace(\"]\", \"\").replace(\" \", \"\");",
    "            String[] parts = line.split(\",\");",
    "            int[] nums = new int[parts.length];",
    "            for (int i = 0; i < parts.length; i++) {",
    "                nums[i] = Integer.parseInt(parts[i]);",
    "            }",
    "",
    "            if (sc.hasNextInt()) {",
    "                int target = sc.nextInt();",
    "                Solution solver = new Solution();",
    "                int[] result = solver.twoSum(nums, target);",
    "                if (result.length == 2) {",
    "                    System.out.println(\"[\" + result[0] + \",\" + result[1] + \"]\");",
    "                } else {",
    "                    System.out.println(\"[]\");",
    "                }",
    "            }",
    "        }",
    "        sc.close();",
    "    }",
    "}"
  ].join("\n"),
};
