import { Difficulty, Language } from "@/generated/prisma";

export const cppSampleData = {
  title: "Two Sum",
  difficulty: Difficulty.EASY,
  tags: ["arrays", "hash-map", "search"],
  description: [
    "Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.",
    "",
    "You may assume that each input would have ***exactly* one solution**, and you may not use the *same* element twice.",
    "",
    "You can return the answer in any order."
  ].join("\n"),
  input: "An integer array nums on the first line (e.g. [2,7,11,15]) and a target integer on the second line (e.g. 9).",
  output: "A JSON-formatted list of two integers representing the 0-indexed positions of the matching numbers (e.g. [0,1]).",
  explanation: "Because nums[0] + nums[1] == 2 + 7 == 9, we return [0, 1].",
  constraints: [
    "2 <= nums.length <= 10^4",
    "-10^9 <= nums[i] <= 10^9",
    "-10^9 <= target <= 10^9",
    "Only one valid answer exists."
  ].join("\n"),
  hints: "Try using an auxiliary hash table to reduce your search complexity to linear O(N) time.",
  editorial: [
    "A brute force approach would inspect every pair of numbers, resulting in O(N^2) complexity.",
    "By maintaining an active hash table mapping visited numbers to their index, we can search for the complement `target - nums[i]` in O(1) average lookup time during our traversal."
  ].join("\n"),
  testCases: [
    {
      input: "[2,7,11,15]\n9",
      expectedOutput: "[0,1]",
      isSample: true,
      isHidden: false,
      explanation: "nums[0] + nums[1] = 2 + 7 = 9. So we return [0, 1].",
      order: 0,
    },
    {
      input: "[3,2,4]\n6",
      expectedOutput: "[1,2]",
      isSample: true,
      isHidden: false,
      explanation: "nums[1] + nums[2] = 2 + 4 = 6. So we return [1, 2].",
      order: 1,
    },
    {
      input: "[3,3]\n6",
      expectedOutput: "[0,1]",
      isSample: false,
      isHidden: true,
      explanation: "nums[0] + nums[1] = 3 + 3 = 6. So we return [0, 1].",
      order: 2,
    },
  ],
  codeSnippets: [
    {
      language: Language.CPP,
      code: [
        "#include <vector>",
        "",
        "class Solution {",
        "public:",
        "    std::vector<int> twoSum(std::vector<int>& nums, int target) {",
        "        // Write your solution here",
        "        ",
        "    }",
        "};"
      ].join("\n"),
    },
  ],
  solutions: [
    {
      language: Language.CPP,
      code: [
        "#include <iostream>",
        "#include <vector>",
        "#include <unordered_map>",
        "#include <string>",
        "#include <sstream>",
        "",
        "// Sandbox compatible solution class implementation",
        "class Solution {",
        "public:",
        "    std::vector<int> twoSum(std::vector<int>& nums, int target) {",
        "        std::unordered_map<int, int> seen;",
        "        for (int i = 0; i < nums.size(); ++i) {",
        "            int complement = target - nums[i];",
        "            if (seen.count(complement)) {",
        "                return {seen[complement], i};",
        "            }",
        "            seen[nums[i]] = i;",
        "        }",
        "        return {};",
        "    }",
        "};",
        "",
        "int main() {",
        "    std::string line;",
        "    if (std::getline(std::cin, line)) {",
        "        // Standard parser to extract integers from flat string e.g., \"[2,7,11,15]\"",
        "        std::vector<int> nums;",
        "        std::string num_str = \"\";",
        "        for (char c : line) {",
        "            if (c == '[' || c == ']' || c == ' ' || c == '\\r' || c == '\\n') continue;",
        "            if (c == ',') {",
        "                if (!num_str.empty()) {",
        "                    nums.push_back(std::stoi(num_str));",
        "                    num_str = \"\";",
        "                }",
        "            } else {",
        "                num_str += c;",
        "            }",
        "        }",
        "        if (!num_str.empty()) {",
        "            nums.push_back(std::stoi(num_str));",
        "        }",
        "",
        "        int target;",
        "        if (std::cin >> target) {",
        "            Solution solver;",
        "            std::vector<int> result = solver.twoSum(nums, target);",
        "            if (result.size() == 2) {",
        "                std::cout << \"[\" << result[0] << \",\" << result[1] << \"]\" << std::endl;",
        "            } else {",
        "                std::cout << \"[]\" << std::endl;",
        "            }",
        "        }",
        "    }",
        "    return 0;",
        "}"
      ].join("\n"),
    },
  ],
};

export const emptyDefaultValues = {
  title: "",
  difficulty: Difficulty.EASY,
  tags: [] as string[],
  description: "",
  input: "",
  output: "",
  explanation: "",
  constraints: "",
  hints: "",
  editorial: "",
  testCases: [
    {
      input: "",
      expectedOutput: "",
      isSample: true,
      isHidden: false,
      explanation: "",
      order: 0,
    },
  ],
  codeSnippets: [
    {
      language: Language.CPP,
      code: [
        "#include <vector>",
        "",
        "class Solution {",
        "public:",
        "    std::vector<int> twoSum(std::vector<int>& nums, int target) {",
        "        ",
        "    }",
        "};"
      ].join("\n"),
    },
  ],
  solutions: [
    {
      language: Language.CPP,
      code: "",
    },
  ],
};
